FROM alpine:3.19

RUN \
  apk update update && apk add --no-cache \
    bash \
    blkid \
    e2fsprogs \
    mdadm \
    nvme-cli \
    util-linux
COPY eks-nvme-ssd-provisioner.sh /usr/local/bin/

ENTRYPOINT ["eks-nvme-ssd-provisioner.sh"]
